version = 0.1

[default.global.parameters]
stack_name = "netops-platform"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
confirm_changeset = false
resolve_s3 = true
region = "us-east-1"
